export const EVENTS_LIST = {
    101 : ["User Allowed",'User'],
    102 : ["User Allowed – with Duress",'User'],
    103 : ["User Allowed – Anti-Pass Back-soft",'User'],
    104 : ["User Allowed - Dead-man Zone",'User'],
    105 : ["User Allowed – Door Not open",'User'],
    106 : ["User Allowed – Smart Secure Access",'User'],
    107 : ["User Allowed – Smart card based route access - soft",'User'],
    108 : ["User Allowed – Panel route access - soft",'User'],
    109 : ["User Allowed – two person rule - primary user",'User'],
    110 : ["User Allowed – two person rule - secondary user",'User'],
    111 : ["Visitor Allowed",'User'],
    112 : ["User Allowed – Multi-Level Access",'User'],
    151 : ["User Denied – User Invalid",'User'],
    152 : ["User Denied – Occupancy Contro",'User'],
    153 : ["User Denied – 2-Person Rule",'User'],
    154 : ["User Denied – Time Out",'User'],
    155 : ["User Denied – Visitor Escort Rule",'User'],
    156 : ["User Denied – Anti-Pass Back",'User'],
    157 : ["User Denied – Disabled User",'User'],
    158 : ["User Denied – Blocked User",'User'],
    159 : ["User Denied – First IN User",'User'],
    160 : ["User Denied – DND Enabled",'User'],
    161 : ["User denied – Control zone",'User'],
    162 : ["User Denied – Door Lock",'User'],
    163 : ["User Denied – Invalid Access Group",'User'],
    164 : ["User Denied – Validity date expired",'User'],
    165 : ["User Denied – Invalid Route Access",'User'],
    166 : ["User Denied – Invalid Shift Access",'User'],
    167 : ["User Denied – Invalid Access Cluster",'User'],
    171 : ["Visitor Denied",'User'],
    172 : ["User Denied – FP sensor busy",'User'],
    201 : ["Door Status changed",'Door'],
    202 : ["Dead-man timer changed",'Controller'],
    203 : ["DND status changed",'Controller'],
    204 : ["Aux input status changed",'Controller'],
    205 : ["Aux output status changed",'Controller'],
    206 : ["Door sense input status",'Door'],
    207 : ["Door Controller Communication status",'Controller'],
    208 : ["Door Open/ Close",'Door'],
    209 : ["Lock relay status changed",'Controller'],
    301 : ["Dead-man timer expired Alarm– User IN",'Alarm'],
    302 : ["Duress detection",'Alarm'],
    303 : ["Panic Alarm",'Alarm'],
    304 : ["FP Memory Full – Alarm",'Alarm'],
    305 : ["Door Held open too long",'Door'],
    306 : ["Door Abnormal",'Door'],
    307 : ["Door force open",'Door'],
    308 : ["Door Controller Offline",'Door'],
    309 : ["Door Controller -Fault",'Door'],
    310 : ["Tamper Alarm",'Alarm'],
    311 : ["Master Controller Mains fail Alarm",'Controller'],
    312 : ["Master Controller Battery fail",'Controller'],
    313 : ["Master Alarm – MC Alarm input",'Controller'],
    314 : ["RTC",'Controller'],
    315 : ["Event Buffer Full",'Controller'],
    317 : ["Intercom - panic",'Controller'],
    318 : ["Occupancy Violated Alarm",'Alarm'],
    319 : ["Tail- Gating Alarm",'Alarm'],
    320 : ["Man Trap Timer Violated Alarm",'Alarm'],
    321 : ["Access Denied Aalrm",'Alarm'],
    322 : ["Multiple Unauthorized Access Alarm",'Alarm'],
    323 : ["Custom Alarm 1",'Alarm'],
    324 : ["Custom Alarm 2",'Alarm'],
    325 : ["Custom Alarm 3",'Alarm'],
    326 : ["User Unidentified",'User'],
    327 : ["Anti-Pass Back Violated Alarm",'Alarm'],
    328 : ["Access Route Violated Alarm",'Alarm'],
    329 : ["Raise Alarm",'Alarm'],
    351 : ["Alarm acknowledged",'Alarm'],
    352 : ["Alarm cleared",'Alarm'],
    353 : ["Alarm Re-issued",'Alarm'],
    401 : ["User Block/Restore",'User'],
    402 : ["Login to ACS",'Controller'],
    403 : ["Message transaction confirmation to ACMS",'Controller'],
    404 : ["Guard Tour-status",'Controller'],
    405 : ["Enrolment",'User'],
    406 : ["Master Alarm sense input status",'Controller'],
    407 : ["Master Aux Output status",'Default'],
    408 : ["Input Output Group Link status",'Default'],
    409 : ["Credentials Deleted",'Controller'],
    410 : ["Time Triggered Function",'Default'],
    411 : ["Time Stamping Function",'Default'],
    412 : ["Guard tag",'Default'],
    413 : ["Camera Event for time stamp",'Default'],
    451 : ["Configuration Change",'Controller'],
    452 : ["Roll over of events",'Controller'],
    453 : ["Master Controller Power ON",'Controller'],
    454 : ["Configuration Defaulted",'Controller'],
    455 : ["Soft Override",'Controller'],
    456 : ["Backup and Update",'Controller'],
    457 : ["Default System",'Controller'],
    458 : ["Sensor Calibration",'Controller'],
    459 : ["User Denied – invalid card",'User'],
    460 : ["User PIN Change",'User'],
};